services:
  HA:
    image: zizutg/net-ub22-host
    container_name: HA
    hostname: HA
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      link-HA-S1:
        ipv4_address: 10.10.1.2
    command: >
      bash -c "
      mkdir -p /tmp
      && tail -f /dev/null
      "

  HB:
    image: zizutg/net-ub22-host
    container_name: HB
    hostname: HB
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      link-HB-S1:
        ipv4_address: 10.10.2.2
    command: >
      bash -c "
      mkdir -p /tmp
      && tail -f /dev/null
      "

  HC:
    image: zizutg/net-ub22-host
    container_name: HC
    hostname: HC
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      link-HC-S1:
        ipv4_address: 10.10.3.2
    command: >
      bash -c "
      mkdir -p /tmp
      && tail -f /dev/null
      "

  S1:
    image: zizutg/multi-l2-switch
    container_name: S1
    hostname: S1
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      link-HA-S1:
        ipv4_address: 10.10.1.3
      link-HB-S1:
        ipv4_address: 10.10.2.3
      link-HC-S1:
        ipv4_address: 10.10.3.3
    command: >
      bash -c "
      mkdir -p /tmp
      && tail -f /dev/null
      "

networks:
  link-HA-S1:
    name: l2-link-HA-S1
    ipam:
      config:
        - subnet: 10.10.1.0/29

  link-HB-S1:
    name: l2-link-HB-S1
    ipam:
      config:
        - subnet: 10.10.2.0/29

  link-HC-S1:
    name: l2-link-HC-S1
    ipam:
      config:
        - subnet: 10.10.3.0/29
